- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- fwoa-tools/package.json
- fwoa-tools/src/export-script.py
- fwoa-tools/src/exportHelper.ts
- fwoa-tools/src/migrationExport.ts
- fwoa-tools/src/migrationUtils.ts
- fwoa-tools/tsconfig.json
Added export functionality and helper scripts. Tested by exporting on test account.
Checklist:
> feat: migration export script

- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- fwoa-tools/.gitignore
- fwoa-tools/package.json
- fwoa-tools/src/exportHelper.ts
- fwoa-tools/src/migrationExport.ts
- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationUtils.ts
This adds the script for the import step of migration. Tested in multiple scenarios on my AWS account successfully. 
Some refactoring of the export as well to prep for future steps and testing.
> feat: migration import script

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/branch-protection.yml
- .github/workflows/build-test-coverage.yml
- .github/workflows/cfn-analysis.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yml
- .github/workflows/deploy-smart.yaml
- .github/workflows/deploy.yaml
- .github/workflows/labeler.yml
- .github/workflows/lint-pr.yml
- .github/workflows/merge-develop-to-stage.yml
- .github/workflows/no-response.yaml
- .github/workflows/pnpm-audit-periodically-with-notification.yml
- .github/workflows/pnpm-audit-pr.yml
- .github/workflows/publish-and-merge-to-develop.yml
- .github/workflows/smart-integ-inferno-test-periodically.yaml
- .github/workflows/solutions-pipeline.yml
- .github/workflows/solutions-pull-request.yml
- .github/workflows/verify-changes.yml
- solutions/smart-deployment/src/lib/bulkExport.ts
- solutions/smart-deployment/src/lib/cdk-infra-stack.ts
- solutions/smart-deployment/src/lib/javaHapiValidator.ts
Description of changes: Added ObjectOwnership for each s3 bucket in smart solution
Checklist:
> fix: object ownership update

- solutions/deployment/lib/cdk-infra-stack.ts
- solutions/deployment/package.json
- solutions/smart-deployment/package.json
- solutions/smart-deployment/src/lib/cdk-infra-stack.ts
> chore: update package versions

- CHANGELOG.md
- solutions/deployment/CHANGELOG.md
- solutions/smart-deployment/CHANGELOG.md
> docs: update changelogs for S3 objectOwnership

- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- fwoa-core/authz-smart/package.json
- fwoa-tools/package.json
- fwoa-tools/src/export-script.py
- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationUtils.ts
- solutions/deployment/package.json
- solutions/smart-deployment/package.json
> test: verification

- solutions/deployment/lib/bulkExportStateMachine.ts
- solutions/deployment/lib/cdk-infra-stack.ts
- solutions/deployment/lib/elasticsearch.ts
- solutions/smart-deployment/src/lib/bulkExportStateMachine.ts
- solutions/smart-deployment/src/lib/cdk-infra-stack.ts
- solutions/smart-deployment/src/lib/elasticsearch.ts
Increase log retention to 10 years
Checklist:
> chore: Increase log retention to 10 years

- fwoa-tools/src/binaryConverter.ts
Fixes so that binary objects that have been deleted can still be imported.
Checklist:
> fix: binary objects

- .viperlightignore
- fwoa-tools/src/binaryConverter.ts
- fwoa-tools/src/migrationExport.ts
Updating folder sorting for multi-tenant deployments
Checklist:
> fix: sorting fix

- fwoa-tools/src/migrationUtils.ts
Update binary verification step
> fix: binary verification

- fwoa-tools/src/export-script.py
> fix: migration export-script performance update

- fwoa-tools/src/binaryConverter.ts
- fwoa-tools/src/exportHelper.ts
- fwoa-tools/src/migrationExport.ts
- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationUtils.ts
Added ability to draw from a previous snapshot via command line args, and general cleanup of export script to match updated glue script. Also made log file continuous.
Checklist:
> fix: export script updates

- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- fwoa-tools/src/migrationUtils.ts
- fwoa-utilities/package.json
- solutions/deployment/package.json
- solutions/smart-deployment/package.json
> chore: version bumps 

- fwoa-tools/src/binaryConverter.ts
- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationVerify.ts
Updated Binary file names and sorted keys before import.
Checklist:
Tested by running end to end on account.
> fix: file name restructure updates

- fwoa-tools/src/migrationExport.ts
- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationUtils.ts
- fwoa-tools/src/migrationVerify.ts
* Centralize configuration check for all scripts 
* Verified export part works 
Checklist:
> refactor: centralize configuration check for scripts

- fwoa-tools/src/migrationImport.ts
Import needs to draw from tenantId folder.
> fix: tenantId for import

- fwoa-tools/src/integration-tests/migrationIntegTests.test.ts
- fwoa-tools/src/migrationUtils.ts
- fwoa-tools/src/migrationVerify.ts
> refactor: remove unused parameter and function, reorganize function

- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationUtils.ts
- fwoa-tools/src/migrationVerify.ts
Switched the import script to use bundles to delete resources instead of individually.
Checklist:
- 
> perf: use bundles for deletion

- fwoa-tools/src/migrationImport.ts
> fix: include tenantId when import from multitenant

- fwoa-tools/package.json
- fwoa-tools/src/migrationExport.test.ts
- fwoa-tools/src/migrationExport.ts
Added unit tests for `migrationExport.ts`
**Test Result**
```
--------------------|---------|----------|---------|---------|-------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------|---------|----------|---------|---------|-------------------
All files           |   10.54 |     9.37 |   11.11 |    10.9 |                   
binaryConverter.ts |       0 |        0 |       0 |       0 | 5-195             
exportHelper.ts    |       0 |        0 |       0 |       0 | 8-131             
migrationExport.ts |     100 |      100 |     100 |     100 |                   
migrationImport.ts |       0 |        0 |       0 |       0 | 5-346             
migrationUtils.ts  |       0 | …
```
> test: migration export unit test

- fwoa-tools/src/migrationImport.ts
Add previously completed folders to current iteration from state file to ensure that future runs also have the previously completed state files.
Checklist:
> fix: import state file

- fwoa-tools/src/migrationVerify.test.ts
- fwoa-tools/src/migrationVerify.ts
Added unit tests for `migrationVerify.ts`
```
--------------------|---------|----------|---------|---------|-------------------------------------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                               
--------------------|---------|----------|---------|---------|-------------------------------------------------
All files           |   76.59 |    54.73 |   78.57 |   76.64 |                                                 
binaryConverter.ts |    73.8 |    55.55 |    62.5 |   74.69 | 45,66,77,108-109,129-132,166-187                
exportHelper.ts    |       0 |        0 |       0 |       0 | 8-131                                           
migrationExport.ts |     100 | …
```
> test: add migrationVerify test

- .gitignore
- fwoa-tools/src/exportHelper.test.ts
--------------------|---------|----------|---------|---------|-------------------------------------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                               
--------------------|---------|----------|---------|---------|-------------------------------------------------
All files           |   72.42 |    58.94 |   71.42 |   72.97 |                                                 
binaryConverter.ts |    73.8 |    55.55 |    62.5 |   74.69 | 45,66,77,108-109,129-132,166-187                
exportHelper.ts    |   97.43 |      100 |     100 |   97.43 | 112                                             
migrationExport.ts |     100 |      100 |     100 |     100 | …
> test: unit test for export util

- CHANGELOG.md
- buildspec.yml
- fwoa-tools/config/jest.config.json
* Update release date in CHANGELOG
* Update buildspec to include all files
* Update jest test threashold 
* Verified Solutions Pipeline passes
Checklist:
> chore: solutions pipeline related updates

- solutions/deployment/scripts/init-auth.py
> fix: Update init-auth.py to use user input

- solutions/deployment/README.md
> docs: Update README.md

- .viperlightignore
- CHANGELOG.md
- README.md
- buildspec.yml
- common/autoinstallers/commitizen/package.json
- common/autoinstallers/commitizen/pnpm-lock.yaml
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- fwoa-tools/package.json
- fwoa-tools/src/binaryConverter.ts
- fwoa-tools/src/migrationImport.ts
- fwoa-tools/src/migrationVerify.ts
- solutions/deployment/CHANGELOG.md
- solutions/deployment/lib/cdk-infra-stack.ts
- solutions/deployment/package.json
- solutions/smart-deployment/CHANGELOG.md
- solutions/smart-deployment/package.json
- solutions/smart-deployment/src/lib/cdk-infra-stack.ts
Small improvements to Migration Tool and documentation updates.
Checklist:
> chore: release v6.1.4
